### PR TITLE
Detect dimension types

### LINKED ISSUE #17: Dimension Names Issue
Currently it's hard coded that spatial dims are x and y, temporal dim is t.
It would be better to handle them dynamically by the names they actually have and assign the spatial and temporal dimensions.

### PR DESCRIPTION
**Pull request by m-mohr**
Tries to fix #17

### CODE REVIEW

**Comment by m-mohr** [comment]
@pierocampa @clausmichele Is there a way to detect whether a dimension is spatial in xarray?

**Comment by pierocampa** [comment]
My experience with `xarray` is zero, so.. only thing I can think of: if there is a CRS attribute attached to it (**and** there is an assumption of 1:1 CRS to m-array correspondence and axis naming), one might fetch the axis label from the CRS definition.

**Comment by clausmichele** [comment]
XArray dataarrays or datasets could have N coordinates (a.k.a. dimensions). The way that Piero describes could be possible only if some attributes are attached to the specific coordinate. Anyway, some more info about coordinates are here: https://docs.xarray.dev/en/stable/user-guide/data-structures.html?highlight=coordinates#coordinates

**Comment by m-mohr** [comment]
So I understand correctly that you can't detect the spatial dimensions automatically, right?

**Comment by clausmichele** [comment]
Exactly

**Pull request merged**
